name: CI workflow

on:
  push:
    branches: [ main ]
    paths:
      - 'api/**' # make sure dependencies in api don't break this repo
      - 'sim/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'api/**' # make sure dependencies in api don't break this repo
      - 'sim/**'

jobs:
  sim_ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r sim/requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 sim --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 sim --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest sim --cov=./sim/resources --cov-report term-missing -m "not (stress)"
