# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# It will test the api when the api undergoes changes

name: Python API Unit Testing

on:
  push:
    branches: [ main ]
    paths: 
      - api/**
  pull_request:
    branches: [ main ]
    paths: 
      - api/**

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f api/requirements.txt ]; then pip install -r api/requirements.txt; fi
        if [ -f api/test-requirements.txt ]; then pip install -r api/test-requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 ./api/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 ./api/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
